apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-service
    spec:
      containers:
        - name: sample-service
          image: ampule/sample-service:kind
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app.kubernetes.io/name: sample-service
  ports:
    - name: http
      port: 8080
      targetPort: http
